import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Vision from '@/components/Vision'
import Projects from '@/components/projects'
import Progress from '@/components/progress'
import About from '@/components/about'
import News from '@/components/news'
import Contact from '@/components/Contact'
import Footer from '@/components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Vision />
        <Projects />
        <Progress />
        <About />
        <News />
        <Contact />
        <Footer />
      </main>
    </>
  )
}
